apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: lsc-maternity-workspace
spec:
  displayName: LSC Maternity Analytics
  description: |
    Shared workspace for LSC Maternity Digital Intelligence team
  validity:
    availableFrom: "2024-04-24"
    expires: "2030-12-31"
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-lsc-maternity-workspace
    resources:
      requests:
        memory: 256M
        cpu: 0.1
      limits:
        memory: 6G
        cpu: 1
