apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: lth-colorectal-generic-workspace
spec:
  displayName: LTH Colorectal Diseases Workspace
  description: |
    Shared workspace for Colorectal Diseases Research  
  validity:
    availableFrom: "2025-05-28"
    expires: "2030-12-31"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-lth-colorectal-generic-workspace
    resources:
      requests:
        memory: "512M"
        cpu: 0.2
      limits:
        memory: "8G"
        cpu: 1