apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterhub
resources:
  - ../shared
  - avoidable-admissions
  - diabetic-foot-ulcer-research
  - arcnwc-chi-se419
  - arcnwc-chi-se421
  - vc-sd-workspace
  - lth-data-science-team-workspace
  - neurosurgery-generic-workspace
  - uhmb-generic-workspace
  - lth-ugi-surgery-generic-workspace
  - lth-finance-workspace
  - nihr-lcrf-workspace
  - lsc-maternity-workspace
  - uom-antimicrobial-workspace
  