apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: llm-gpu-workspace
spec:
  displayName: LLM GPU Workspace
  description: |
    Workspace for research into Large Language Models using Ollama and GPU
  validity:
    availableFrom: "2025-01-01"
    expires: "2030-12-31"

  jupyterWorkspace:
    image: lscsde/llm-workspace:0.1.7
    persistentVolumeClaim:
      name: jupyter-llm-gpu-workspace
    resources:
      requests: #cpu and memory to possibly be adjusted
        nvidia.com/gpu: 1
        memory: "8G"
        cpu: 0.5
      limits:
        nvidia.com/gpu: 1
        memory: "12G"
        cpu: 2
    tolerations:
      - key: "xlscsde.nhs.uk/appType"
        value: "llm-gpu-workspace"
        effect: "NoSchedule"
