apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: vc-sd-workspace
spec:
  displayName: VC-SD Workspace
  description: |
    Shared workspace for VC and SD
  
  validity:
    availableFrom: "2022-05-01"
    expires: "2025-12-31"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-vc-sd-workspace
