apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: sqlmesh-workspace-zuber-ismail
  labels:
    app: sqlmesh
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  displayName: SQLMesh Data Engineering Workspace (Zuber Ismail)
  description: SQLMesh Data Engineering Workspace (Zuber Ismail)
  validity:
    availableFrom: "2024-12-22"
    expires: "2030-12-31"
  jupyterWorkspace:
    image: ghcr.io/lsc-sde/docker-dataengineering-sqlmesh-notebook:sqlmesh-0.216.0
    persistentVolumeClaim:
      name: jupyter-sqlmesh-workspace-zuber-ismail
    resources:
      requests:
        memory: "512M"
        cpu: 0.1
      limits:
        memory: "2G"
        cpu: 0.5
---
apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspaceBinding
metadata:
  name: sqlmesh-workspace-zuber-ismail
  labels:
    app: sqlmesh
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  workspace: sqlmesh-workspace-zuber-ismail
  username: "zuber.ismail@lthtr.nhs.uk"
  expires: "2030-01-01"
