apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: advanced-generic-workspace
spec:
  displayName: Advanced Generic Workspace
  description: |
    Advanced environment for testing with Python R and Julia.
  
  validity:
    availableFrom: "2022-01-01"
    expires: "2030-01-01"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-advanced-generic-workspace
