apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: mph-omop-workspace
spec:
  displayName: DARWIN Workspace
  description: |
    Darwin v1.4.0 omop workspace
  
  validity:
    availableFrom: "2022-05-01"
    expires: "2025-12-31"
  
  jupyterWorkspace:
    image: lscsde/datascience-jupyter-omop:darwinv1-0.1.111
    persistentVolumeClaim: 
      name: jupyter-mph-omop-workspace
---
apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: metrics-test-workspace
spec:
  displayName: Metrics Test Workspace
  description: |
    Metrics test workspace
  
  validity:
    availableFrom: "2022-05-01"
    expires: "2025-12-31"
  
  jupyterWorkspace:
    image: lscsde/datascience-jupyter-omop:darwinv1-0.1.111
    persistentVolumeClaim: 
      name: jupyter-metrics-test-workspace