apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: lth-ugi-surgery-generic-workspace
spec:
  displayName: LTH UGI Surgery Generic Workspace
  description: |
    All work must be stored in /home/jovyan/lth-ugi-surgery-generic-workspace. 
    Any work saved outside of this folder will be lost between sessions.
  validity:
    availableFrom: "2024-07-08"
    expires: "2030-01-01"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-lth-ugi-surgery-generic-workspace
    resources:
      requests:
        memory: "2G"
        cpu: 0.1
      limits:
        memory: "6G"
        cpu: 1
