apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: uom-antimicrobial-workspace
spec:
  displayName: Antimicrobial Prescribing Research
  description: |
    Collaboration with University of Manchester
  validity:
    availableFrom: "2024-08-06"
    expires: "2030-12-31"
  jupyterWorkspace:
    image: lscsde/datascience-jupyter-omop:darwinv1-0.1.93
    persistentVolumeClaim: 
      name: jupyter-uom-antimicrobial-workspace
    resources:
      requests:
        memory: 30G
        cpu: 3
      limits:
        memory: 32G
        cpu: 8
    tolerations:
    - key: "xlscsde.nhs.uk/nodeSize"
      operator: "Equal"
      value: "large"
      effect: "NoSchedule"
    - key: "xlscsde.nhs.uk/appType"
      operator: "Equal"
      value: "datascience-notebook"
      effect: "NoSchedule"
