apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: uom-antimicrobial-workspace
spec:
  displayName: Antimicrobial Prescribing Research
  description: |
    Collaboration with University of Manchester
  validity:
    availableFrom: "2024-08-06"
    expires: "2030-12-31"
  jupyterWorkspace:
    image: lscsde/datascience-jupyter-omop:darwinv1-0.1.93
    persistentVolumeClaim: 
      name: jupyter-uom-antimicrobial-workspace
    resources:
      requests:
        memory: 256M
        cpu: 0.1
      limits:
        memory: 6G
        cpu: 1
