apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: cr8tor-test-workspace
spec:
  displayName: cr8tor-test Workspace
  description: |
    Workspace for testing cr8tor
  validity:
    availableFrom: "2025-06-01"
    expires: "2025-12-31"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-cr8tor-test-workspace
