name: Update core repository

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  semver:
    uses: lsc-sde/lsc-sde/.github/workflows/semver.yaml@main
    with:
      useConfigFile: true

  submodule:
    uses: lsc-sde/lsc-sde/.github/workflows/update-submodules.yaml@main
    needs: 
    - semver
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      directory: products/sde/analytics-workspace-management/iac-flux-workspace-definitions
    secrets: inherit